# Generated by Django 5.1.4 on 2024-12-24 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Toy_factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SantasList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('niceness_coefficient', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toy', to='Toy_factory.toy')),
                ('santas_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids', to='Santa_list.santaslist')),
            ],
        ),
    ]
