# Generated by Django 5.1.4 on 2024-12-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toy_factory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coal',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='toy',
            name='production_time',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='toy',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
